### ISSUE TITLE
Union Find の計算量

### ISSUE THREAD

**Issue by ia7ck** [ngtkana/ac-adapter-rs#112]
Union Find でマージテクが正しく行われておらず、計算量が悪くなっているように見えます。

↓の箇所で、頂点を swap した直後、元に戻している⚠ことが原因です。

https://github.com/ngtkana/ac-adapter-rs/blob/b9e53bd7acb6c92d4cab5b72fbc62f4a7b5c02f6/crates/algolib/union_find/src/lib.rs#L33-L34

**Comment by ngtkana** [comment]
ありがとうございます。イシューを放置しており、気づかずで申し訳ありません。 このイシューよりあとの PR #133 で治っていたようです。
